### ISSUE TITLE
centos 7上中文显示乱码，有解决办法么

### ISSUE THREAD

**Issue by chenwenkun** [lxrmido/node-paper-calendar#2]
![image](https://user-images.githubusercontent.com/42236131/62749824-70adb500-ba90-11e9-831e-d60c3646253f.png)

**Comment by chenwenkun** [comment]
![image](https://user-images.githubusercontent.com/42236131/62749847-93d86480-ba90-11e9-8dbd-f51891d43a9a.png)

**Comment by lxrmido** [comment]
应该是系统中没中文字体导致的，尝试下安装中文字体
